[package]
name = "miniloop"
version = "0.1.0"
edition = "2021"
resolver = "2"
license = "Apache-2.0"
keywords = ["executor"]
categories = ["no-std", "no-std::no-alloc", "asynchronous"]

[dependencies]

[[example]]
name = "simple"